name: train-my-model

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: iterative/setup-cml@v1

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: cml
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ls
          
          pip3 install -r requirements.txt
          python training/train.py
          
          echo "## MODEL METRICS" >> report.md
          cat training/outputs/metrics.txt >> report.md
          
          echo "## Data viz" >> report.md
          cml-publish training/outputs/feature_importance.png --md >> report.md
          cml-publish training/outputs/residuals.png --md >> report.md
          
          cml-send-comment report.md
          
          
